services:
  backend:
    build: ./backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8.0
    container_name: book_store-db-1
    environment:
      MYSQL_DATABASE: bookstore_db
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      # THÊM DÒNG NÀY: Giả sử file sql của Bảo tên là database_backup.sql
      - ./database_backup.sql:/docker-entrypoint-initdb.d/backup.sql

  backend:
    build: ./backend
    container_name: book_store-backend-1
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql+pymysql://root:admin@db/bookstore_db

  frontend:
    build: ./frontend
    container_name: book_store-frontend-1
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mysql_data: